name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.4
  firebase_core: ^1.15.0
  firebase_auth: ^3.3.16
  cloud_firestore: ^3.1.13
  modal_progress_hud: ^0.1.3

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/logo.png